# Generated by Django 3.0.7 on 2020-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_title',
            new_name='comment_text',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(height_field=100, null=True, upload_to='article/', width_field=100),
        ),
    ]
