# Generated by Django 3.0.7 on 2020-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField(default=10)),
                ('health', models.IntegerField(default=100)),
                ('energy', models.IntegerField(default=100)),
                ('satiety', models.IntegerField(default=100)),
                ('money', models.IntegerField(default=1000)),
            ],
        ),
    ]
